version: '3.7'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appheslo
      MYSQL_DATABASE: postnet-db
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  server:
    container_name: postnet-server
    restart: unless-stopped
    build: ./postnet-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/postnet-db
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=appheslo
      - JWT_SECRET=PostNet
    depends_on:
      - db

  client:
    container_name: postnet-client
    build:
      dockerfile: ./postnet-client/Dockerfile
      context: .
    ports:
      - "3000:3000"

volumes:
  my-db: