/* tslint:disable */
/* eslint-disable */
/**
 * POSTNET API
 * API k semestrální práce z PIA
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Přepravka pro nastavení admin role
 * @export
 * @interface AdminRoleVO
 */
export interface AdminRoleVO {
    /**
     * 
     * @type {number}
     * @memberof AdminRoleVO
     */
    userId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleVO
     */
    admin?: boolean;
}


