/* tslint:disable */
/* eslint-disable */
/**
 * POSTNET API
 * API k semestrální práce z PIA
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Přepravka pro přihlašovací údaje
 * @export
 * @interface CredentialsVO
 */
export interface CredentialsVO {
    /**
     * 
     * @type {string}
     * @memberof CredentialsVO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialsVO
     */
    password: string;
}


