/* tslint:disable */
/* eslint-disable */
/**
 * PIA API
 * API semestrální práce z PIA
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JwtRequestVO
 */
export interface JwtRequestVO {
    /**
     * 
     * @type {string}
     * @memberof JwtRequestVO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof JwtRequestVO
     */
    password: string;
}


