/* tslint:disable */
/* eslint-disable */
/**
 * PIA API
 * API semestrální práce z PIA
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import axios from "axios"
import * as Api from './api'

export * from "./configuration";
export * from "./model";

let baseURL = 'http://localhost:8080'
let baseAxios = axios.create({baseURL, headers: { Pragma: "no-cache"}})

const UserApi = new Api.UserControllerApi(undefined, baseURL, baseAxios)
const PostsApi = new Api.PostControllerApi(undefined, baseURL, baseAxios)
const FriendshipApi = new Api.FriendshipControllerApi(undefined, baseURL, baseAxios)
const AdminApi = new Api.AdminControllerApi(undefined, baseURL, baseAxios)

export {
    UserApi,
    PostsApi,
    FriendshipApi,
    AdminApi
}
